print("Berapa nilai penjumlahan dari bilangan berikut, jika x = 250, y = 250, z = 250!!")
x = eval(input("x = "))
y = eval(input("y = "))
z = eval(input("z = "))
print ("Hasil dari penjumlahan x,y,z adalah", (x + y + z))